DAY_ORDER = {
    "MONDAY": 1,
    "TUESDAY": 2,
    "WEDNESDAY": 3,
    "THURSDAY": 4,
    "FRIDAY": 5,
    "SATURDAY": 6,
    "SUNDAY": 7,
}

UNSCHEDULED_SESSION_PENALTY = 10000
ROOM_CAPACITY_GAP_PENALTY = 3
SAME_SUBJECT_SAME_DAY_PENALTY = 25
FACULTY_BACK_TO_BACK_PENALTY = 10
